### ISSUE TITLE
ボスチェックリスト（BossChecklist）

### ISSUE THREAD

**Issue by Katudonsan** [Katudonsan/TMLHonyaku#11]
[元Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2669644269)

**Comment by Katudonsan** [comment]
翻訳完了

**Comment by Katudonsan** [comment]
翻訳した際にどうしてもエラーが出るため修正求む

**Comment by eva828Dev** [comment]
ExternalLocalizerに"表示"などの一部文字列が読み込めないバグがあったことが原因でした。現在は修正済みです。

また、ローダーがhjsonのリストと認識することを防ぐために、299,231,233,241行目をダブルクォーテーションで囲む必要がありそうです。

`QueenBee: [i:1133]を使うか、ジャングルの蜂の巣で幼虫を見つけて壊す` 
-> `QueenBee: "[i:1133]を使うか、ジャングルの蜂の巣で幼虫を見つけて壊す"`

**Comment by eva828Dev** [comment]
ExternalLocalizerに"表示"などの一部文字列が読み込めないバグがあったことが原因でした。現在は修正済みです。

また、ローダーがhjsonのリストと認識することを防ぐために、299,231,233,241行目をダブルクォーテーションで囲む必要がありそうです。

`QueenBee: [i:1133]を使うか、ジャングルの蜂の巣で幼虫を見つけて壊す`
-> `QueenBee: "[i:1133]を使うか、ジャングルの蜂の巣で幼虫を見つけて壊す"`

**Comment by Katudonsan** [comment]
ありがとうございます

**Comment by Katudonsan** [comment]
修正し、プッシュしましたが、
ボスチェックリスト閲覧中にクトゥルフの脳を閲覧したところフリーズしたため
別翻訳ミスが発生したと思われます
なので、タグは据え置きとします

**Comment by Katudonsan** [comment]
また、evaさまも翻訳に参加されますか？

**Comment by eva828Dev** [comment]
> 修正し、プッシュしましたが、 ボスチェックリスト閲覧中にクトゥルフの脳を閲覧したところフリーズしたため 別翻訳ミスが発生したと思われます なので、タグは据え置きとします

バージョン0.1.7にて、フリーズの件修正しました。ボスチェックリストのメッセージボックスがワイド文字に非対応だったことによるバグだったようです。

> また、evaさまも翻訳に参加されますか？

お誘いいただきありがとうございます。現在、Modのバグ修正や機能追加を行っているので、落ち着き次第参加させていただこうと考えています。

**Comment by Katudonsan** [comment]
ありがとうございます、お待ちしておりますね！

**Comment by Katudonsan** [comment]
招待だけ先に送信させていただきました。

**Comment by Katudonsan** [comment]
バグ検証中ですが、仮で翻訳完了に移動します
